### ISSUE TITLE
[FEATURE] New dashboard-maps plugin for hosting maps code base

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/maps#14]
**Is your feature request related to a problem?**
New dashboard-maps plugin for hosting maps code base
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1408

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by Shivamdhar** [comment]
Closing in the favor of https://github.com/opensearch-project/dashboards-maps.
