### ISSUE TITLE
[FEATURE] Document how to run your own maps server

### ISSUE THREAD

**Issue by dblock** [opensearch-project/maps#27]
**Is your feature request related to a problem?**

I'd like to run my own maps server and configure OpenSearch Dashboards to point to it. How do I do that?

**What solution would you like?**
- A how-to guide to run this server myself on, for example, AWS.
- A DEVELOPER_GUIDE and/or link in the README to [this](https://github.com/opensearch-project/maps/blob/main/opensearch-maps-server/README.md)

**Comment by junqiu-lei** [comment]
Hi @dblock, we are working on the docker hub release review for the [OpenSearch Maps Server](https://github.com/opensearch-project/maps/tree/main/opensearch-maps-server), the docker image is used for users who want to self-host a maps server using for OpenSearch , accompany with the image release, we will add doc to tell user how to use it.

**Comment by junqiu-lei** [comment]
The doc for how to run localhost maps server posted at opensearch.org website: https://opensearch.org/docs/latest/dashboards/selfhost-maps-server/

**Comment by dblock** [comment]
Thanks @junqiu-lei. Just need some links in the README to close this I believe?

**Comment by junqiu-lei** [comment]
Thanks @dblock, will update README.

**Comment by junqiu-lei** [comment]
Close this issue since document updated.
