### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/maps#37]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
Permissions are incorrect. You have 10+ people with maintain access. Please work with admin to sync.

![Screenshot 2023-03-23 at 10 58 11 AM](https://user-images.githubusercontent.com/542335/227244099-087a4a77-e4e7-4215-ba0f-3d6964465859.png)

**Comment by junqiu-lei** [comment]
Thanks @dblock, just updated the maintain access permission to individual alias based on [CODEOWNERS](https://github.com/opensearch-project/maps/blob/main/.github/CODEOWNERS), thanks @peterzhuamazon help

**Comment by dblock** [comment]
There should be 3 maintainers according to maintainers file. This is what I see in settings.

<img width="834" alt="Screenshot 2023-03-30 at 10 30 36 AM" src="https://user-images.githubusercontent.com/542335/228869664-983c8538-700a-47dd-b671-8ae4763a3d62.png">

**Comment by junqiu-lei** [comment]
Hi @dblock , the maintainers are updated, could you help double check? Thank you!

**Comment by dblock** [comment]
Doesn't look correct. You have all these people with write access that should not have it, only folks in MAINTAINERS should have maintain access.  Please work with an admin on fixing it?

![Screenshot 2023-04-04 at 12 11 10 PM](https://user-images.githubusercontent.com/542335/229853062-a0f9a9ab-455c-4dc4-a758-fc330820a4b8.png)

**Comment by junqiu-lei** [comment]
Updated, please help check whenever you get a chance, thanks! @dblock 

![Screenshot 2023-04-04 at 12 22 32 PM](https://user-images.githubusercontent.com/90288540/229856693-b3cb65a0-f2be-4487-a1d0-450f4b78aaba.png)

**Comment by dblock** [comment]
Verified, thx. I added Triage group with triage permissions as well.
