### ISSUE TITLE
[FEATURE] support for more zoom levels

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/maps#4]
**Is your feature request related to a problem?**
Currently we have zoom level of 10 but we would need to further increase to 20.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by glitchcube** [comment]
Hi, is there any progress on this issue?

**Comment by glitchcube** [comment]
That's great news! Do you guys have any estimat on when this feature will be done and available?
Are we talking weeks, months or years?

**Comment by elfisher** [comment]
@vamshin and @junqiu-lei can we add the v2.1 label to this since it is aiming for the 2.1 release?

**Comment by vamshin** [comment]
Hi @elfisher. Added 2.1 tag. 

In this release, we will enable zoom levels up to 14 from current 10 on existing rastar tiles. One good thing about this is customers will be able to get these zoom levels for all OSD versions(1.x, 2,x) with out any upgrade to their clusters as changes are enabled from Maps backend server. We will time the release of changes with 2.1 release time line scheduled for June 30.

Vector tiles support will be incorporated in dashboards part of 3.0 release which will enable up to zoom levels 22. This is part of Maps revamp where we introduce layers. One such layer will be vector tiles https://github.com/opensearch-project/maps/issues/10
