### ISSUE TITLE
[FEATURE] Support for high resolution Tiles images

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/maps#5]
**Is your feature request related to a problem?**
As of today, tiles images quality reduces as we expand, we would like to Support for high resolution Tiles images

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by junqiu-lei** [comment]
Since 2.5.0, new Maps plugin released out with vector tiles map layer https://github.com/opensearch-project/dashboards-maps/issues/61, which is a high resolution tiles map. Closing this issue.
